In [1]:
!export PYTHONPATH=${PYTHONPATH}:/home/sai/PythonRobotics/PathPlanning/CubicSpline

In [3]:
from ppo_control import PPOControl
import cubic_spline_planner
import matplotlib.pyplot as plt
import time
import numpy as np
import math
%matplotlib tk

In [4]:
husky_ppo = PPOControl()

In [5]:
ax = [0.0,6.0, 12.5, 14.0, 17.5, 20.0, 25.0] 
ay = [0.0,-3.0, -5.0, -4, 3.0, 2, 0.0]
cx, cy, cyaw, ck, s = cubic_spline_planner.calc_spline_course(ax, ay, ds= 0.5)
plt.plot(cx, cy, "+")
plt.show()
cv = [1.0]*len(cx)
husky_ppo.set_waypoints_from_list(cx, cy, cyaw, cv)

In [7]:
husky_ppo.read_waypoint_file("./unity_waypoints_bkp.txt")
#husky_ppo.read_waypoint_file("ww.txt")
cx = [i[0] for i in husky_ppo.waypoints_list]
cy = [i[1] for i in husky_ppo.waypoints_list]
plt.plot(cx, cy, "+")
plt.show()

In [6]:
def simulate_warthog(X, v, w, dt):
    xcurr = X[0] + v*math.cos(X[2])*dt
    ycurr = X[1] + v*math.sin(X[2])*dt
    thcurr = X[2]+w*dt
    return [xcurr, ycurr, thcurr]

In [7]:
#husky_ppo.set_pose([30.67, -33.33, 3.06])
#husky_ppo.set_pose([120.180, -78.957, 140*math.pi/180.])
#husky_ppo.set_pose([132.180, -78.957, 160*math.pi/180.])
husky_ppo.set_twist([0. , 0.])
husky_ppo.set_pose([0. , 0.5, 7*math.pi/4])
husky_ppo.read_ppo_policy("./model1.zip")
#husky_ppo.read_tf_frozen_graph("/home/sai/hdd1/ml-master/ml-agents/config/ppo/results/wlong_path52/3DBall/frozen_graph_def.pb")

Using cpu device
Wrapping the env in a DummyVecEnv.


/home/administrator/anaconda3/envs/pytorch_rospy/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:704: UserWarning: A pickle file created using an old (<=1.4.1) version of cloudpicke is currently being loaded. This is not supported by cloudpickle and will break in cloudpickle 1.7
  "will break in cloudpickle 1.7", category=UserWarning


In [8]:
x_pose = []
y_pose = []
for i in range(0, 2000):
    obs = husky_ppo.get_observation()
    twist = husky_ppo.get_ppo_control(np.array(obs).reshape(1,42))[0]
    print(twist)
    v = np.clip(twist[0][0], 0, 1) * 4.0
    w = np.clip(twist[0][1], -1, 1) * 2.5
    current_pose = simulate_warthog(husky_ppo.get_pose(), v, w, 0.05)
    print(twist[0], current_pose)
    husky_ppo.set_pose(current_pose)
    husky_ppo.set_twist([v, w])
    x_pose.append(current_pose[0])
    y_pose.append(current_pose[1])
    print(husky_ppo.closest_idx, husky_ppo.closest_dist)

[[1.        0.8127955]]
[1.        0.8127955] [0.14142135623730948, 0.35857864376269044, 5.5993865837607375]
0 0.5
[[-1.       -0.895103]]
[-1.       -0.895103] [0.14142135623730948, 0.35857864376269044, 5.487498711541652]
0 0.3854590039974296
[[ 1.        -0.0997131]]
[ 1.        -0.0997131] [0.28138024931340067, 0.215709793942601, 5.475034573793768]
0 0.3854590039974296
[[-1.        -0.8999515]]
[-1.        -0.8999515] [0.28138024931340067, 0.215709793942601, 5.3625406340960255]
0 0.35454979890902616
[[1.         0.47689575]]
[1.         0.47689575] [0.4024416748811738, 0.05651139181651646, 5.422152602792143]
0 0.35454979890902616
[[-1.         -0.70953953]]
[-1.         -0.70953953] [0.4024416748811738, 0.05651139181651646, 5.333460161209463]
1 0.26162744524819787
[[1.         0.83447725]]
[1.         0.83447725] [0.518823002484969, -0.10613972740858477, 5.437769816935419]
1 0.26162744524819787
[[-1.         -0.60893583]]
[-1.         -0.60893583] [0.518823002484969, -0.106139727408

[[1.         0.75249076]]
[1.         0.75249076] [11.272993367436742, -5.734572840689123, 6.4312614889148465]
24 0.5819572811480631
[[-1.         -0.40464342]]
[-1.         -0.40464342] [11.272993367436742, -5.734572840689123, 6.380681061864256]
24 0.5981259137155326
[[1.         0.77046895]]
[1.         0.77046895] [11.472043577922152, -5.715104566350752, 6.476989680648207]
24 0.5981259137155326
[[-1.         -0.43285796]]
[-1.         -0.43285796] [11.472043577922152, -5.715104566350752, 6.4228824355903855]
25 0.5523964233354826
[[1.         0.74716496]]
[1.         0.74716496] [11.67009522081016, -5.687255926359518, 6.516278056174873]
25 0.5523964233354826
[[-1.         -0.42525703]]
[-1.         -0.42525703] [11.67009522081016, -5.687255926359518, 6.463120927781223]
25 0.5268858994652174
[[1.         0.75999135]]
[1.         0.75999135] [11.866866264123253, -5.651462679601552, 6.558119846254944]
25 0.5268858994652174
[[-1.        -0.4289408]]
[-1.        -0.4289408] [11.8668662641

[[-1.         -0.32850432]]
[-1.         -0.32850432] [20.676517299964488, 0.8325079939388597, 5.800297538031249]
54 0.7719338604812777
[[1.        0.7838788]]
[1.        0.7838788] [20.853648842876495, 0.7396402573151425, 5.898282388437896]
54 0.7719338604812777
[[-1.         -0.35806325]]
[-1.         -0.35806325] [20.853648842876495, 0.7396402573151425, 5.853524482090383]
54 0.7659966635767423
[[1.        0.7719641]]
[1.        0.7719641] [21.035470260777668, 0.6563277612991966, 5.950019991238027]
54 0.7659966635767423
[[-1.         -0.33596423]]
[-1.         -0.33596423] [21.035470260777668, 0.6563277612991966, 5.908024462152629]
54 0.8008483935177609
[[1.        0.7796093]]
[1.        0.7796093] [21.22156000012989, 0.5830433229249982, 6.005475627471118]
54 0.8008483935177609
[[-1.         -0.34378237]]
[-1.         -0.34378237] [21.22156000012989, 0.5830433229249982, 5.962502831805854]
55 0.7672625174502619
[[1.       0.537175]]
[1.       0.537175] [21.41136410275072, 0.5200004595

[[-0.57991487  1.        ]]
[-0.57991487  1.        ] [24.030200826826142, -1.1932679990660382, 13.48476352377644]
61 1.447157407573593
[[-0.60307956  1.        ]]
[-0.60307956  1.        ] [24.030200826826142, -1.1932679990660382, 13.60976352377644]
61 1.447157407573593
[[-0.63114005  1.        ]]
[-0.63114005  1.        ] [24.030200826826142, -1.1932679990660382, 13.73476352377644]
61 1.447157407573593
[[-0.6664091  1.       ]]
[-0.6664091  1.       ] [24.030200826826142, -1.1932679990660382, 13.85976352377644]
61 1.447157407573593
[[-0.7102081  1.       ]]
[-0.7102081  1.       ] [24.030200826826142, -1.1932679990660382, 13.98476352377644]
61 1.447157407573593
[[-0.7617095  1.       ]]
[-0.7617095  1.       ] [24.030200826826142, -1.1932679990660382, 14.10976352377644]
61 1.447157407573593
[[-0.8184598  1.       ]]
[-0.8184598  1.       ] [24.030200826826142, -1.1932679990660382, 14.23476352377644]
61 1.447157407573593
[[-0.8785604  1.       ]]
[-0.8785604  1.       ] [24.0302008268

[[ 0.18641046 -1.        ]]
[ 0.18641046 -1.        ] [24.79017842774867, -1.4817104056669566, 18.50451546369901]
61 1.735366994147119
[[ 0.16231854 -1.        ]]
[ 0.16231854 -1.        ] [24.82072878272094, -1.4926907600298915, 18.37951546369901]
61 1.751900538601295
[[ 0.19107817 -1.        ]]
[ 0.19107817 -1.        ] [24.85479993006549, -1.5099994751174564, 18.25451546369901]
61 1.7702750134728356
[[ 0.16185704 -1.        ]]
[ 0.16185704 -1.        ] [24.881607528689223, -1.5281450171476285, 18.12951546369901]
61 1.7961040142430278
[[ 0.19319208 -1.        ]]
[ 0.19319208 -1.        ] [24.91065508036073, -1.5536237715849224, 18.00451546369901]
61 1.821069124100064
[[ 0.15754287 -1.        ]]
[ 0.15754287 -1.        ] [24.931567353010518, -1.5771921207249378, 17.87951546369901]
61 1.8539318012585424
[[ 0.19284327 -1.        ]]
[ 0.19284327 -1.        ] [24.95336890823209, -1.6090077350035608, 17.75451546369901]
61 1.8827035948204502
[[ 0.14982073 -1.        ]]
[ 0.14982073 -1.     

61 2.3978387984948553
[[ 0.05904928 -1.        ]]
[ 0.05904928 -1.        ] [25.224783542779107, -2.0199774883234762, 19.019484180238454]
61 2.3972377158196885
[[ 0.06082906 -1.        ]]
[ 0.06082906 -1.        ] [25.23677412905623, -2.0179201079438407, 18.894484180238454]
61 2.3980899423117354
[[ 0.06685913 -1.        ]]
[ 0.06685913 -1.        ] [25.250132460706045, -2.017319537215592, 18.769484180238454]
61 2.4005327303190778
[[ 0.06776014 -1.        ]]
[ 0.06776014 -1.        ] [25.26364106755021, -2.018403512508948, 18.644484180238454]
61 2.4048946104963256
[[ 0.0731117 -1.       ]]
[ 0.0731117 -1.       ] [25.277957016177105, -2.021381167706194, 18.519484180238454]
61 2.410940492034856
[[ 0.07282671 -1.        ]]
[ 0.07282671 -1.        ] [25.291736107036364, -2.0261019535120597, 18.394484180238454]
61 2.4191056564863547
[[ 0.07743555 -1.        ]]
[ 0.07743555 -1.        ] [25.305647086633513, -2.032908952986278, 18.269484180238454]
61 2.428734169582435
[[ 0.07556343 -1.       

[[-0.00814209 -1.        ]]
[-0.00814209 -1.        ] [25.473246755771445, -2.2075300686390262, 19.564304893583415]
61 2.667775873265866
[[ 1.7404184e-04 -1.0000000e+00]]
[ 1.7404184e-04 -1.0000000e+00] [25.47327304506235, -2.2075072542656806, 19.439304893583415]
61 2.667775873265866
[[ 0.00819608 -1.        ]]
[ 0.00819608 -1.        ] [25.47463536491973, -2.2065956005225287, 19.314304893583415]
61 2.6677661318689454
[[ 0.00845253 -1.        ]]
[ 0.00845253 -1.        ] [25.47614656539019, -2.2058379186647086, 19.189304893583415]
61 2.6675076674242555
[[ 0.01608992 -1.        ]]
[ 0.01608992 -1.        ] [25.47918060481028, -2.2047655238874735, 19.064304893583415]
61 2.6674523701400754
[[ 0.01616357 -1.        ]]
[ 0.01616357 -1.        ] [25.482339062903367, -2.204076625553775, 18.939304893583415]
61 2.6677518552803177
[[ 0.02343065 -1.        ]]
[ 0.02343065 -1.        ] [25.4870063330466, -2.2036566145376324, 18.814304893583415]
61 2.66845541339488
[[ 0.02302938 -1.        ]]
[ 0.0

[[-0.06430486 -1.        ]]
[-0.06430486 -1.        ] [25.576195547438534, -2.2736750076058962, 19.968780019998906]
61 2.7716713211271276
[[-0.05637218 -1.        ]]
[-0.05637218 -1.        ] [25.576195547438534, -2.2736750076058962, 19.843780019998906]
61 2.7716713211271276
[[-0.04841983 -1.        ]]
[-0.04841983 -1.        ] [25.576195547438534, -2.2736750076058962, 19.718780019998906]
61 2.7716713211271276
[[-0.04051124 -1.        ]]
[-0.04051124 -1.        ] [25.576195547438534, -2.2736750076058962, 19.593780019998906]
61 2.7716713211271276
[[-0.03269529 -1.        ]]
[-0.03269529 -1.        ] [25.576195547438534, -2.2736750076058962, 19.468780019998906]
61 2.7716713211271276
[[-0.02500504 -1.        ]]
[-0.02500504 -1.        ] [25.576195547438534, -2.2736750076058962, 19.343780019998906]
61 2.7716713211271276
[[-0.01745869 -1.        ]]
[-0.01745869 -1.        ] [25.576195547438534, -2.2736750076058962, 19.218780019998906]
61 2.7716713211271276
[[-0.01006263 -1.        ]]
[-0.01

[[-0.05724307 -1.        ]]
[-0.05724307 -1.        ] [25.616566240255644, -2.3042847824191934, 19.65015359011328]
61 2.816997766271027
[[-0.0496095 -1.       ]]
[-0.0496095 -1.       ] [25.616566240255644, -2.3042847824191934, 19.52515359011328]
61 2.816997766271027
[[-0.04208926 -1.        ]]
[-0.04208926 -1.        ] [25.616566240255644, -2.3042847824191934, 19.40015359011328]
61 2.816997766271027
[[-0.03471043 -1.        ]]
[-0.03471043 -1.        ] [25.616566240255644, -2.3042847824191934, 19.27515359011328]
61 2.816997766271027
[[-0.02748819 -1.        ]]
[-0.02748819 -1.        ] [25.616566240255644, -2.3042847824191934, 19.15015359011328]
61 2.816997766271027
[[-0.02042912 -1.        ]]
[-0.02042912 -1.        ] [25.616566240255644, -2.3042847824191934, 19.02515359011328]
61 2.816997766271027
[[-0.01353794 -1.        ]]
[-0.01353794 -1.        ] [25.616566240255644, -2.3042847824191934, 18.90015359011328]
61 2.816997766271027
[[-0.00682744 -1.        ]]
[-0.00682744 -1.        

[[-0.04278334 -1.        ]]
[-0.04278334 -1.        ] [25.635842345111215, -2.32040805351796, 19.292987549424527]
61 2.840050375520477
[[-0.03566094 -1.        ]]
[-0.03566094 -1.        ] [25.635842345111215, -2.32040805351796, 19.167987549424527]
61 2.840050375520477
[[-0.02870767 -1.        ]]
[-0.02870767 -1.        ] [25.635842345111215, -2.32040805351796, 19.042987549424527]
61 2.840050375520477
[[-0.0219309 -1.       ]]
[-0.0219309 -1.       ] [25.635842345111215, -2.32040805351796, 18.917987549424527]
61 2.840050375520477
[[-0.01534381 -1.        ]]
[-0.01534381 -1.        ] [25.635842345111215, -2.32040805351796, 18.792987549424527]
61 2.840050375520477
[[-0.0089768 -1.       ]]
[-0.0089768 -1.       ] [25.635842345111215, -2.32040805351796, 18.667987549424527]
61 2.840050375520477
[[-0.00289171 -1.        ]]
[-0.00289171 -1.        ] [25.635842345111215, -2.32040805351796, 18.542987549424527]
61 2.840050375520477
[[ 0.00280339 -1.        ]]
[ 0.00280339 -1.        ] [25.63637

[[-0.01883491 -1.        ]]
[-0.01883491 -1.        ] [25.646236368685546, -2.329224604998336, 18.780502399176715]
61 2.852604711444885
[[-0.01258475 -1.        ]]
[-0.01258475 -1.        ] [25.646236368685546, -2.329224604998336, 18.655502399176715]
61 2.852604711444885
[[-0.00663464 -1.        ]]
[-0.00663464 -1.        ] [25.646236368685546, -2.329224604998336, 18.530502399176715]
61 2.852604711444885
[[-0.00109968 -1.        ]]
[-0.00109968 -1.        ] [25.646236368685546, -2.329224604998336, 18.405502399176715]
61 2.852604711444885
[[ 0.00384082 -1.        ]]
[ 0.00384082 -1.        ] [25.646930034178148, -2.329554610768545, 18.280502399176715]
61 2.852604711444885
[[ 0.00377896 -1.        ]]
[ 0.00377896 -1.        ] [25.64756672140141, -2.32996185758413, 18.155502399176715]
61 2.853212360577654
[[ 0.00642908 -1.        ]]
[ 0.00642908 -1.        ] [25.648555076604556, -2.330784340807771, 18.030502399176715]
61 2.853863260644226
[[ 0.00437763 -1.        ]]
[ 0.00437763 -1.      

[[-0.001972 -1.      ]]
[-0.001972 -1.      ] [25.652619309154606, -2.334787083036267, 18.35856424473774]
61 2.860451388650605
[[ 0.00259941 -1.        ]]
[ 0.00259941 -1.        ] [25.653077775392507, -2.3350322078021346, 18.23356424473774]
61 2.860451388650605
[[ 0.00336342 -1.        ]]
[ 0.00336342 -1.        ] [25.653626821169112, -2.3354208635875975, 18.10856424473774]
61 2.860877429699239
[[ 0.00452114 -1.        ]]
[ 0.00452114 -1.        ] [25.65429396000096, -2.3360312353440427, 17.98356424473774]
61 2.861472486930954
[[ 0.0032654 -1.       ]]
[ 0.0032654 -1.       ] [25.654717080211164, -2.33652871063653, 17.85856424473774]
61 2.8623187352729733
[[ 0.00212174 -1.        ]]
[ 0.00212174 -1.        ] [25.65494956362876, -2.336883707159185, 17.73356424473774]
61 2.862953869179674
[[-0.00220665 -1.        ]]
[-0.00220665 -1.        ] [25.65494956362876, -2.336883707159185, 17.60856424473774]
61 2.8633756554475664
[[-0.00923014 -1.        ]]
[-0.00923014 -1.        ] [25.65494956

[[-0.11110187 -1.        ]]
[-0.11110187 -1.        ] [25.656828581142143, -2.3385713644352095, 20.330943396003807]
61 2.86573133467084
[[-0.10417315 -1.        ]]
[-0.10417315 -1.        ] [25.656828581142143, -2.3385713644352095, 20.205943396003807]
61 2.86573133467084
[[-0.09699422 -1.        ]]
[-0.09699422 -1.        ] [25.656828581142143, -2.3385713644352095, 20.080943396003807]
61 2.86573133467084
[[-0.08964199 -1.        ]]
[-0.08964199 -1.        ] [25.656828581142143, -2.3385713644352095, 19.955943396003807]
61 2.86573133467084
[[-0.08219448 -1.        ]]
[-0.08219448 -1.        ] [25.656828581142143, -2.3385713644352095, 19.830943396003807]
61 2.86573133467084
[[-0.07472554 -1.        ]]
[-0.07472554 -1.        ] [25.656828581142143, -2.3385713644352095, 19.705943396003807]
61 2.86573133467084
[[-0.06729982 -1.        ]]
[-0.06729982 -1.        ] [25.656828581142143, -2.3385713644352095, 19.580943396003807]
61 2.86573133467084
[[-0.05996975 -1.        ]]
[-0.05996975 -1.    

[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.06584677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.19084677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.31584677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.44084677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.56584677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.69084677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.81584677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 19.94084677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 20.06584677255329]
61 2.869285434982937
[[-1.  1.]]
[-1.  1.] [25.659664700923383, -2.3411163826689996, 

[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 18.73974256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 18.86474256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 18.98974256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.11474256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.23974256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.36474256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.48974256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.61474256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.73974256000098]
61 2.871947895822661
[[-1.  1.]]
[-1.  1.] [25.661742412497148, -2.343046313276765, 19.8647425

In [9]:
plt.cla()
plt.plot(x_pose, y_pose, '+g')
plt.plot(cx, cy, "+b")
#plt.xlim([0, 25])
#plt.ylim([-20, 7])

In [ ]:
obs = husky_ppo.get_observation()

In [ ]:
print(obs)

In [ ]:
print(husky_ppo.get_pose())

In [ ]:
husky_ppo.closest_idx

In [ ]:
2*math.pi - 6.1321

In [ ]:
i = 0
while i < len(obs)-3:
    print([obs[i], obs[i+1], obs[i+2], obs[i+3]])
    i = i + 4

In [ ]:
obs2 = [ 3.1718987e-01,  2.6397274e+00, -7.1165800e-02,  2.9253261e+00,
         8.2946199e-01,  2.4810174e+00, -2.3757100e-01,  2.9868939e+00,
         1.4194126e+00,  2.3704438e+00, -3.9009976e-01,  2.9857869e+00,
         2.0244434e+00,  2.2775273e+00, -4.8208833e-01,  3.2309980e+00,
         2.5908678e+00,  2.2095571e+00, -5.5408025e-01,  3.0272779e+00,
         3.1385303e+00,  2.1544523e+00, -5.6134295e-01,  2.8097680e+00,
         3.6512144e+00,  2.1172132e+00, -5.9754920e-01,  2.6893539e+00,
         4.2099533e+00,  2.0821514e+00, -6.1818290e-01,  2.6712611e+00,
         4.7472596e+00,  2.0539546e+00, -6.3812470e-01,  2.9293561e+00,
         5.2431216e+00,  2.0312028e+00, -6.4151406e-01,  2.9405370e+00,
         3.7776546e-03, -1.4553810e-03]

In [ ]:
i = 0
while i < len(obs2)-3:
    print([obs2[i], obs2[i+1], obs2[i+2], obs2[i+3]])
    i = i + 4

In [ ]:
print(husky_ppo.num_waypoints)

In [20]:
print(husky_ppo.waypoints_list)

[array([0.        , 0.        , 5.84690706, 4.        ]), array([ 0.43545074, -0.20302535,  5.84595374,  4.        ]), array([ 0.87129576, -0.40674059,  5.84405479,  4.        ]), array([ 1.30792936, -0.61183558,  5.8412255 ,  4.        ]), array([ 1.74574581, -0.81900022,  5.83748844,  4.        ]), array([ 2.1851394 , -1.02892438,  5.83287314,  4.        ]), array([ 2.62650443, -1.24229795,  5.82741558,  4.        ]), array([ 3.07023516, -1.4598108 ,  5.82115759,  4.        ]), array([ 3.5167259 , -1.68215281,  5.81414619,  4.        ]), array([ 3.96637093, -1.91001388,  5.80643284,  4.        ]), array([ 4.41956452, -2.14408387,  5.79807264,  4.        ]), array([ 4.87670098, -2.38505267,  5.78912349,  4.        ]), array([ 5.33817457, -2.63361015,  5.77964528,  4.        ]), array([ 5.8043796 , -2.89044621,  5.77000864,  4.        ]), array([ 6.27566617, -3.15603351,  5.76509605,  4.        ]), array([ 6.75167852, -3.42737363,  5.76856828,  4.        ]), array([ 7.23149358, -3.6986